SHELL := /bin/bash
FREQUENCY = 8.0
asap7_area:
	# perl ./genus_area.pl -w ASAP7 top_4_64_top      $(FREQUENCY)
	# perl ./genus_area.pl -w ASAP7 top_8_64_top	   $(FREQUENCY)
	# perl ./genus_area.pl -w ASAP7 top_16_64_top	   $(FREQUENCY)
	perl ./genus_area.pl -w ASAP7 RCA_64bit_top	   $(FREQUENCY)
	# perl ./genus_area.pl -w ASAP7 top16block_top  $(FREQUENCY)
	# perl ./genus_area.pl -w ASAP7 top8block_top	   $(FREQUENCY)
	# perl ./genus_area.pl -w ASAP7 top4block_top	   $(FREQUENCY)
	# perl ./genus_area.pl -w ASAP7 BK_adder_64_16bit_top	        $(FREQUENCY)
	# perl ./genus_area.pl -w ASAP7 BK_64_with_8_block_top         $(FREQUENCY) 
	# perl ./genus_area.pl -w ASAP7 KSA_64_bit   $(FREQUENCY)
	# perl ./genus_area.pl -w ASAP7 CLA_shi_top                    $(FREQUENCY)
	# perl ./genus_area.pl -w ASAP7 CLA_HAN_SHI_top                $(FREQUENCY)
	# perl ./genus_area.pl -w ASAP7 CLA_4_bit_old_top              $(FREQUENCY)
	# perl ./genus_area.pl -w ASAP7 CLA_8_bit_old_top              $(FREQUENCY)
	# perl ./genus_area.pl -w ASAP7 CLA_16_bit_old_top             $(FREQUENCY)
	# perl ./genus_area.pl -w ASAP7 CLA_HAN_32bit_block_64bit_top $(FREQUENCY)
	# perl ./genus_area.pl -w ASAP7 CLA_HAN_shi_8_top               $(FREQUENCY)	
asap7:
	perl ./tempus.pl -w ASAP7 top_4_64_top      $(FREQUENCY)
	perl ./tempus.pl -w ASAP7 top_8_64_top	   $(FREQUENCY)
	perl ./tempus.pl -w ASAP7 top_16_64_top	   $(FREQUENCY)
	perl ./tempus.pl -w ASAP7 RCA_64bit_top	   $(FREQUENCY)
	perl ./tempus.pl -w ASAP7 top16block_top  $(FREQUENCY)
	perl ./tempus.pl -w ASAP7 top8block_top	   $(FREQUENCY)
	perl ./tempus.pl -w ASAP7 top4block_top	   $(FREQUENCY)
	perl ./tempus.pl -w ASAP7 BK_adder_64_16bit_top	        $(FREQUENCY)
	perl ./tempus.pl -w ASAP7 BK_64_with_8_block_top         $(FREQUENCY) 
	perl ./tempus.pl -w ASAP7 KSA_64_bit   $(FREQUENCY)
	perl ./tempus.pl -w ASAP7 CLA_shi_top                    $(FREQUENCY)
	perl ./tempus.pl -w ASAP7 CLA_HAN_SHI_top                $(FREQUENCY)
	perl ./tempus.pl -w ASAP7 CLA_4_bit_old_top              $(FREQUENCY)
	perl ./tempus.pl -w ASAP7 CLA_8_bit_old_top              $(FREQUENCY)
	perl ./tempus.pl -w ASAP7 CLA_16_bit_old_top             $(FREQUENCY)
	perl ./tempus.pl -w ASAP7 CLA_HAN_32bit_block_64bit_top $(FREQUENCY)
	perl ./tempus.pl -w ASAP7 CLA_HAN_shi_8_top               $(FREQUENCY)	
cnfet7_area:
	perl ./genus_area.pl -w CNFET7 top_4_64_top      $(FREQUENCY)
	perl ./genus_area.pl -w CNFET7 top_8_64_top	   $(FREQUENCY)
	perl ./genus_area.pl -w CNFET7 top_16_64_top	   $(FREQUENCY)
	perl ./genus_area.pl -w CNFET7 RCA_64bit_top	   $(FREQUENCY)
	perl ./genus_area.pl -w CNFET7 top16block_top  $(FREQUENCY)
	perl ./genus_area.pl -w CNFET7 top8block_top	   $(FREQUENCY)
	perl ./genus_area.pl -w CNFET7 top4block_top	   $(FREQUENCY)
	perl ./genus_area.pl -w CNFET7 BK_adder_64_16bit_top	        $(FREQUENCY)
	perl ./genus_area.pl -w CNFET7 BK_64_with_8_block_top         $(FREQUENCY) 
	perl ./genus_area.pl -w CNFET7 KSA_64_bit   $(FREQUENCY)
	perl ./genus_area.pl -w CNFET7 CLA_shi_top                    $(FREQUENCY)
	perl ./genus_area.pl -w CNFET7 CLA_HAN_SHI_top                $(FREQUENCY)
	perl ./genus_area.pl -w CNFET7 CLA_4_bit_old_top              $(FREQUENCY)
	perl ./genus_area.pl -w CNFET7 CLA_8_bit_old_top              $(FREQUENCY)
	perl ./genus_area.pl -w CNFET7 CLA_16_bit_old_top             $(FREQUENCY)
	perl ./genus_area.pl -w CNFET7 CLA_HAN_32bit_block_64bit_top $(FREQUENCY)
	perl ./genus_area.pl -w CNFET7 CLA_HAN_shi_8_top               $(FREQUENCY)	
cnfet5:
	# perl ./tempus.pl -w CNFET5 top_4_64_top      $(FREQUENCY)
	# perl ./tempus.pl -w CNFET5 top_8_64_top	   $(FREQUENCY)
	# perl ./tempus.pl -w CNFET5 top_16_64_top	   $(FREQUENCY)
	# perl ./tempus.pl -w CNFET5 RCA_64bit_top	   $(FREQUENCY)
	# perl ./tempus.pl -w CNFET5 top16block_top  $(FREQUENCY)
	# perl ./tempus.pl -w CNFET5 top8block_top	   $(FREQUENCY)
	# perl ./tempus.pl -w CNFET5 top4block_top	   $(FREQUENCY)
	perl ./tempus.pl -w CNFET5 BK_adder_64_16bit_top	        $(FREQUENCY)
	perl ./tempus.pl -w CNFET5 BK_64_with_8_block_top         $(FREQUENCY) 
	# perl ./tempus.pl -w CNFET5 KSA_64_bit   $(FREQUENCY)
	# perl ./tempus.pl -w CNFET5 CLA_shi_top                    $(FREQUENCY)
	# perl ./tempus.pl -w CNFET5 CLA_HAN_SHI_top                $(FREQUENCY)
	# perl ./tempus.pl -w CNFET5 CLA_4_bit_old_top              $(FREQUENCY)
	# perl ./tempus.pl -w CNFET5 CLA_8_bit_old_top              $(FREQUENCY)
	# perl ./tempus.pl -w CNFET5 CLA_16_bit_old_top             $(FREQUENCY)
	# perl ./tempus.pl -w CNFET5 CLA_HAN_32bit_block_64bit_top $(FREQUENCY)
	# perl ./tempus.pl -w CNFET5 CLA_HAN_shi_8_top               $(FREQUENCY)
cnfet7:
	perl ./tempus.pl -w CNFET7 top_4_64_top      $(FREQUENCY)
	perl ./tempus.pl -w CNFET7 top_8_64_top	   $(FREQUENCY)
	perl ./tempus.pl -w CNFET7 top_16_64_top	   $(FREQUENCY)
	perl ./tempus.pl -w CNFET7 RCA_64bit_top	   $(FREQUENCY)
	perl ./tempus.pl -w CNFET7 top16block_top  $(FREQUENCY)
	perl ./tempus.pl -w CNFET7 top8block_top	   $(FREQUENCY)
	perl ./tempus.pl -w CNFET7 top4block_top	   $(FREQUENCY)
	perl ./tempus.pl -w CNFET7 BK_adder_64_16bit_top	        $(FREQUENCY)
	perl ./tempus.pl -w CNFET7 BK_64_with_8_block_top         $(FREQUENCY) 
	perl ./tempus.pl -w CNFET7 KSA_64_bit   $(FREQUENCY)
	perl ./tempus.pl -w CNFET7 CLA_shi_top                    $(FREQUENCY)
	perl ./tempus.pl -w CNFET7 CLA_HAN_SHI_top                $(FREQUENCY)
	perl ./tempus.pl -w CNFET7 CLA_4_bit_old_top              $(FREQUENCY)
	perl ./tempus.pl -w CNFET7 CLA_8_bit_old_top              $(FREQUENCY)
	perl ./tempus.pl -w CNFET7 CLA_16_bit_old_top             $(FREQUENCY)
	perl ./tempus.pl -w CNFET7 CLA_HAN_32bit_block_64bit_top $(FREQUENCY)
	perl ./tempus.pl -w CNFET7 CLA_HAN_shi_8_top               $(FREQUENCY)	
run:
	source ./run.sh
	source ./run_area.sh
clean:
	rm -f *cmd* *.log* *.run
	rm -f RCDB*
	rm -f run.sh
	rm -f .ssv_emulate_view_definition*.tcl
	rm -f *.tcl
get_data:
	python3 ./_read_area.py
	python3 ./_read_wire_power.py
	python3 ./_read_wiredelay.py
	python3 /home/shi/tempus/_read_wire_data.py
	